- job:
    name: Pipeline-test-job
    project-type: pipeline
    sandbox: true
    pipeline-scm:
      scm:
        - git:
            url: https://github.com/anilkps199/Sample_maven_pjt.git
            # clean: true
            branches:
               - origin/master
      script-path: Jenkinsfile
      lightweight-checkout: true
